version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
  db:
    image: postgres
    restart: always
    env_file:
      - ".env"
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
