'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      'Products',
      [
        {
          id: 0,
          quantity: 57,
          price: 1422,
          compareAtPrice: 1815,
        },
        {
          id: 1,
          quantity: 141,
          price: 52,
          compareAtPrice: 675,
        },
        {
          id: 2,
          quantity: 32,
          price: 570,
          compareAtPrice: 603,
        },
        {
          id: 3,
          quantity: 48,
          price: 737,
          compareAtPrice: 344,
        },
        {
          id: 4,
          quantity: 116,
          price: 504,
          compareAtPrice: 1677,
        },
        {
          id: 5,
          quantity: 74,
          price: 1583,
          compareAtPrice: 338,
        },
        {
          id: 6,
          quantity: 107,
          price: 1340,
          compareAtPrice: 632,
        },
        {
          id: 7,
          quantity: 193,
          price: 1711,
          compareAtPrice: 1294,
        },
        {
          id: 8,
          quantity: 8,
          price: 1757,
          compareAtPrice: 1615,
        },
        {
          id: 9,
          quantity: 118,
          price: 555,
          compareAtPrice: 1895,
        },
        {
          id: 10,
          quantity: 166,
          price: 1722,
          compareAtPrice: 1973,
        },
        {
          id: 11,
          quantity: 149,
          price: 316,
          compareAtPrice: 17,
        },
        {
          id: 12,
          quantity: 53,
          price: 108,
          compareAtPrice: 1695,
        },
        {
          id: 13,
          quantity: 32,
          price: 1049,
          compareAtPrice: 1431,
        },
        {
          id: 14,
          quantity: 61,
          price: 327,
          compareAtPrice: 810,
        },
        {
          id: 15,
          quantity: 49,
          price: 1195,
          compareAtPrice: 227,
        },
        {
          id: 16,
          quantity: 106,
          price: 243,
          compareAtPrice: 1242,
        },
        {
          id: 17,
          quantity: 68,
          price: 645,
          compareAtPrice: 1260,
        },
        {
          id: 18,
          quantity: 102,
          price: 576,
          compareAtPrice: 1776,
        },
        {
          id: 19,
          quantity: 186,
          price: 204,
          compareAtPrice: 188,
        },
        {
          id: 20,
          quantity: 35,
          price: 1480,
          compareAtPrice: 1150,
        },
        {
          id: 21,
          quantity: 10,
          price: 438,
          compareAtPrice: 227,
        },
        {
          id: 22,
          quantity: 80,
          price: 963,
          compareAtPrice: 1107,
        },
        {
          id: 23,
          quantity: 167,
          price: 635,
          compareAtPrice: 1935,
        },
        {
          id: 24,
          quantity: 180,
          price: 1016,
          compareAtPrice: 1582,
        },
        {
          id: 25,
          quantity: 74,
          price: 166,
          compareAtPrice: 1166,
        },
        {
          id: 26,
          quantity: 94,
          price: 1749,
          compareAtPrice: 1361,
        },
        {
          id: 27,
          quantity: 169,
          price: 352,
          compareAtPrice: 1610,
        },
        {
          id: 28,
          quantity: 81,
          price: 26,
          compareAtPrice: 522,
        },
        {
          id: 29,
          quantity: 37,
          price: 740,
          compareAtPrice: 758,
        },
        {
          id: 30,
          quantity: 99,
          price: 801,
          compareAtPrice: 1117,
        },
        {
          id: 31,
          quantity: 4,
          price: 526,
          compareAtPrice: 1744,
        },
        {
          id: 32,
          quantity: 141,
          price: 1956,
          compareAtPrice: 925,
        },
        {
          id: 33,
          quantity: 110,
          price: 1777,
          compareAtPrice: 1964,
        },
        {
          id: 34,
          quantity: 32,
          price: 1216,
          compareAtPrice: 842,
        },
        {
          id: 35,
          quantity: 55,
          price: 328,
          compareAtPrice: 685,
        },
        {
          id: 36,
          quantity: 28,
          price: 1607,
          compareAtPrice: 736,
        },
        {
          id: 37,
          quantity: 42,
          price: 90,
          compareAtPrice: 1672,
        },
        {
          id: 38,
          quantity: 42,
          price: 467,
          compareAtPrice: 1725,
        },
        {
          id: 39,
          quantity: 192,
          price: 1819,
          compareAtPrice: 1574,
        },
        {
          id: 40,
          quantity: 21,
          price: 1238,
          compareAtPrice: 1542,
        },
        {
          id: 41,
          quantity: 19,
          price: 19,
          compareAtPrice: 1612,
        },
        {
          id: 42,
          quantity: 124,
          price: 56,
          compareAtPrice: 635,
        },
        {
          id: 43,
          quantity: 91,
          price: 197,
          compareAtPrice: 1632,
        },
        {
          id: 44,
          quantity: 195,
          price: 1432,
          compareAtPrice: 1746,
        },
        {
          id: 45,
          quantity: 51,
          price: 201,
          compareAtPrice: 896,
        },
        {
          id: 46,
          quantity: 60,
          price: 432,
          compareAtPrice: 752,
        },
        {
          id: 47,
          quantity: 128,
          price: 106,
          compareAtPrice: 1277,
        },
        {
          id: 48,
          quantity: 42,
          price: 478,
          compareAtPrice: 963,
        },
        {
          id: 49,
          quantity: 178,
          price: 551,
          compareAtPrice: 1870,
        },
      ],
      {},
    );
  },

  down: async (queryInterface, Sequelize) => {},
};
